site_name: OneV's Notes
pages:
- 主页: index.md
- 笔记:
    - 逆向工程:
        - 工具: reserve-enginnering/tools.md
    - Swift:
        - Advanced Swift: swift/advanced-swift.md
        - Reactive Cocoa: swift/rac.md
    - iOS:
        - Spotligt Search: iOS/spotlight.md
    - Elixir:
        - Basic: elixir/basic.md
    - NSHipster: nshipster/index.md
    - 摄影:
        - Photoshop: photo/photoshop.md
    - 收藏链接: misc/link.md
    - 未分类: misc/uncategory.md
